### ISSUE TITLE
No sound on iPhone 14 Pro Max and can one do multiple flags or even program the property list by some trigger

### ISSUE THREAD

**Issue by kwccoin** [elfketchup/SporkVN#2]
No sound on my iPhone 14 Pro Max but it looks very nice.  And only landscape mode which I accept as it is good.

For my 2 old iPad Air , both mode work and sound ok.    But you cannot switch the landscape and portrait mid-game.  And auto-save would have some issues.

My M2 MacBook Air 15" (as iPad) obviously only test landscape but sound ok and it is basically work.

Obviously sample is just a sample and hence I will dig a bit longer.  Thanks again.

I will keep this for a few days in case you want to know or want to recruit some tester.

---

Not really an issue but more a feature not sure.  Can one handle multiple flags so what can be displayed or what path to go depends upon multiple and not just one flag? 

 I am more a programmer and hence wonder whether one need to actually program the property list and if so when one can trigger a program to modify it?

**Comment by elfketchup** [comment]
Is your iPhone 14 Pro Max on silent mode? No sound will play if your phone's mute switch is on.

SporkVN isn't designed to switch between landscape or portrait... so far, I've never seen any other visual novel do it, and it seems like it would be more trouble than it's worth. If someone else wants to add the functionality, that's great, but I don't think it's worth the effort.

Auto-save can act oddly since it's based on NSUserDefaults / UserDefaults class. If you wait 5 to 10 seconds after the .SYSTEMCALL:AUTOSAVE command is called (and maybe tap on the screen and move to the next few lines of dialogue), UserDefaults should sync within that time so you can exit and reload.

There's no single command for handling multiple flags, but some conditional commands can be "nested." If you had flags A, B, and C, and wanted something to run if they all were set to a value of 1, you would do something like:

.ISFLAG:A:1:.ISFLAG:B:1:.ISFLAG:C:1:(some command runs here)

The scripts are programmed in the property list just because it was the easiest method and I'm very lazy.

SporkVN is meant as a simple/easy/lazy visual novel open-source project. If you want something that has a LOT more features and is easier to work with, I recommend Ren'Py, which is also cross-platform: https://www.renpy.org/
